import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/common/http';
import '@angular/http';
import '@angular/router';
import 'rxjs';
// import 'tslib';
// import '@ng-bootstrap/ng-bootstrap';
// import 'ng2-dnd';
